import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import SharedLayout from "./components/layout/SharedLayout";

import { ThemeProvider } from "@/components/theme-provider"

import { Toaster } from "@/components/ui/toaster"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script src="/scripts/bsv.browser.min.js" strategy="beforeInteractive" />
        <Script src="/scripts/message.js" strategy="beforeInteractive" />
        <Script src="/scripts/idb.js" strategy="beforeInteractive" />
        <Script src="/scripts/SHUAllet_plugin.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SharedLayout>
              {children}
              <Toaster />
            </SharedLayout>
          </ThemeProvider>
        
      </body>
    </html>
  );
}
